[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"
  NETLIFY_USE_PYTHON = "false"

# Redirects and headers are NGINX-style redirects and headers
# For more information see https://docs.netlify.com/routing/redirects/

# Remove the redirect that's causing issues with Next.js
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"
